[toolchain]

[features]
resolution = true
seeds = false
skip-lint = false

[programs.devnet]
payment_engine = "AeaX15Xn4YCSLGBvf1EMdjHViewi28odizgfyQ3RLD9e"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arthurbretas1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000


